# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-12 19:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name')),
                ('middlename', models.CharField(blank=True, max_length=200, null=True, verbose_name='Middlename')),
                ('lastname', models.CharField(blank=True, max_length=200, null=True, verbose_name='Lastname')),
                ('second_lastname', models.CharField(blank=True, max_length=200, null=True, verbose_name='SecondLastname')),
                ('gender', models.CharField(blank=True, choices=[(b'-', b'Seleccione'), (b'f', b'Femenino'), (b'm', b'Masculino')], default=b'-', max_length=1, null=True, verbose_name='Gender')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('rut', models.CharField(blank=True, error_messages={b'unique': 'UniqueRUTError'}, max_length=20, null=True, unique=True, verbose_name='RUT')),
                ('serie', models.CharField(blank=True, max_length=120, null=True, verbose_name='Serie')),
                ('rut_verified', models.BooleanField(default=False, verbose_name='RUTVerified')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=b'profileimages/%Y', verbose_name='ProfilePicture')),
                ('cellphone', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Cellphone')),
                ('sms_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Code')),
                ('cellphone_verified', models.BooleanField(default=False, verbose_name='PhoneVerified')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Perfiles',
            },
        ),
    ]
