# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-12 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lastname',
            field=models.CharField(default=b'', max_length=200, verbose_name='Lastname'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default=b'', max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rut',
            field=models.CharField(blank=True, error_messages={b'unique': 'Rut debe ser unico'}, max_length=20, null=True, unique=True, verbose_name='RUT'),
        ),
    ]
