# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-10 15:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='workflow.Workflow')),
            ],
            options={
                'verbose_name': 'feedback',
            },
        ),
        migrations.CreateModel(
            name='FeedbackDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Pendiente'), (2, 'Leido'), (3, 'Sin Respuesta'), (4, 'Respondido')], default=1, verbose_name='Status')),
                ('comment_comp', models.TextField(blank=True, null=True, verbose_name='Comentario de empresa')),
                ('comment_user', models.TextField(blank=True, null=True, verbose_name='Comentario de usuario')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.Feedback')),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fb_user_from', to=settings.AUTH_USER_MODEL)),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fb_user_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'feedback',
            },
        ),
    ]
