# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-10 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackdetails',
            options={'verbose_name': 'lista', 'verbose_name_plural': 'Listado de feedbacks'},
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='name',
            new_name='workflow',
        ),
    ]
