# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-10 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowquestion',
            options={'verbose_name': 'Pregunta'},
        ),
        migrations.AlterModelOptions(
            name='workflowtypes',
            options={'verbose_name': 'Tipo', 'verbose_name_plural': 'Tipos de workflow'},
        ),
    ]
